name: Deploy Next.js to Google Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Next.js Project
        run: |
          npm run build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: cloud-agah-agah

      - name: Debug Authentication
        run: gcloud auth list

      - name: Upload Files to GCS
        run: |
          gsutil -m rsync -r ./out gs://code98.app
